version: 2
multi-ecosystem-groups:
  all:
    schedule:
      interval: weekly
      day: friday
      time: "08:00"
      timezone: Etc/UTC
updates:
  - package-ecosystem: github-actions
    directory: "/"
    multi-ecosystem-group: all
    patterns:
      - "*"
    allow:
      - dependency-type: all
